-- Esquema PostgreSQL para Neon.
-- Conserva los nombres de tablas y columnas que utiliza la aplicación Java.
-- Ejecutar conectado a la base de datos neondb, no crear otra base de datos.


CREATE TABLE categoria (
    id_categoria INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(80) NOT NULL,
    descripcion VARCHAR(255),
    activo BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE metodo_pago (
    id_metodo_pago INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(60) NOT NULL,
    activo BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE tipo_documento (
    id_tipo_documento INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    descripcion VARCHAR(100) NOT NULL,
    efecto_en_inventario SMALLINT NOT NULL CHECK (efecto_en_inventario IN (1, -1))
);

CREATE TABLE cargo (
    id_cargo INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(80) NOT NULL,
    descripcion VARCHAR(255)
);

CREATE TABLE persona (
    id_persona INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tipo VARCHAR(20) NOT NULL CHECK (tipo IN ('CLIENTE', 'EMPLEADO', 'PROVEEDOR')),
    nombres VARCHAR(100) NOT NULL,
    apellidos VARCHAR(100) NOT NULL,
    documento VARCHAR(20) NOT NULL UNIQUE,
    telefono VARCHAR(30),
    email VARCHAR(120) UNIQUE,
    direccion VARCHAR(255),
    activo BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE cliente (
    id_persona INTEGER PRIMARY KEY REFERENCES persona(id_persona),
    fecha_registro DATE NOT NULL DEFAULT CURRENT_DATE,
    contrasena_hash VARCHAR(64)
);

CREATE TABLE empleado (
    id_persona INTEGER PRIMARY KEY REFERENCES persona(id_persona),
    id_cargo INTEGER NOT NULL REFERENCES cargo(id_cargo),
    fecha_ingreso DATE NOT NULL DEFAULT CURRENT_DATE,
    contrasena_hash VARCHAR(64) NOT NULL,
    salario NUMERIC(12, 2) DEFAULT 0
);

CREATE TABLE proveedor (
    id_persona INTEGER PRIMARY KEY REFERENCES persona(id_persona),
    nombre_empresa VARCHAR(150) NOT NULL,
    nit VARCHAR(30) UNIQUE
);

CREATE TABLE producto (
    id_producto INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_categoria INTEGER NOT NULL REFERENCES categoria(id_categoria),
    nombre VARCHAR(150) NOT NULL,
    descripcion TEXT,
    precio_compra NUMERIC(12, 2) NOT NULL,
    precio_venta NUMERIC(12, 2) NOT NULL,
    stock_actual INTEGER NOT NULL DEFAULT 0,
    stock_minimo INTEGER NOT NULL DEFAULT 0,
    imagen_url VARCHAR(255) NOT NULL DEFAULT 'assets/img/default.png',
    activo BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE documento (
    id_documento INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_tipo_documento INTEGER NOT NULL REFERENCES tipo_documento(id_tipo_documento),
    id_persona INTEGER NOT NULL REFERENCES persona(id_persona),
    id_empleado INTEGER REFERENCES empleado(id_persona) ON DELETE SET NULL,
    id_metodo_pago INTEGER REFERENCES metodo_pago(id_metodo_pago),
    fecha_documento TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    numero_doc_externo VARCHAR(60),
    subtotal NUMERIC(14, 2) NOT NULL DEFAULT 0,
    descuento NUMERIC(14, 2) NOT NULL DEFAULT 0,
    total NUMERIC(14, 2) NOT NULL DEFAULT 0,
    estado VARCHAR(20) NOT NULL DEFAULT 'COMPLETADA'
        CHECK (estado IN ('PENDIENTE', 'COMPLETADA', 'ANULADA')),
    observaciones TEXT
);

CREATE TABLE movimiento_inventario (
    id_movimiento INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_documento INTEGER NOT NULL REFERENCES documento(id_documento),
    id_producto INTEGER NOT NULL REFERENCES producto(id_producto),
    id_empleado INTEGER REFERENCES empleado(id_persona) ON DELETE SET NULL,
    cantidad INTEGER NOT NULL,
    precio_unitario NUMERIC(12, 2) NOT NULL DEFAULT 0,
    subtotal_linea NUMERIC(14, 2) GENERATED ALWAYS AS
        (cantidad * precio_unitario) STORED,
    fecha_movimiento TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE carrito (
    id_carrito INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_cliente INTEGER NOT NULL REFERENCES cliente(id_persona),
    creado_en TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE item_carrito (
    id_item INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_carrito INTEGER NOT NULL REFERENCES carrito(id_carrito) ON DELETE CASCADE,
    id_producto INTEGER NOT NULL REFERENCES producto(id_producto),
    cantidad INTEGER NOT NULL DEFAULT 1 CHECK (cantidad > 0),
    CONSTRAINT uq_carrito_producto UNIQUE (id_carrito, id_producto)
);

CREATE INDEX idx_producto_nombre ON producto(nombre);
CREATE INDEX idx_producto_categoria ON producto(id_categoria);
CREATE INDEX idx_producto_activo ON producto(activo);
CREATE INDEX idx_documento_persona ON documento(id_persona);
CREATE INDEX idx_documento_fecha ON documento(fecha_documento);
CREATE INDEX idx_movimiento_producto ON movimiento_inventario(id_producto);
CREATE INDEX idx_movimiento_documento ON movimiento_inventario(id_documento);

CREATE OR REPLACE VIEW vista_persona_cliente AS
SELECT p.id_persona, p.nombres AS nombre, p.apellidos AS apellido,
       p.documento, p.telefono, p.email, p.direccion, p.activo,
       c.contrasena_hash
FROM persona p
JOIN cliente c ON c.id_persona = p.id_persona
WHERE p.tipo = 'CLIENTE' AND p.activo = TRUE;

INSERT INTO tipo_documento (descripcion, efecto_en_inventario) VALUES
    ('Factura de Venta al Cliente', -1),
    ('Factura de Compra a Proveedor', 1),
    ('Devolucion del Cliente', 1),
    ('Devolucion a Proveedor', -1),
    ('Ajuste de Inventario (Entrada)', 1),
    ('Ajuste de Inventario (Salida)', -1),
    ('Baja por mercancia en mal estado', -1);

INSERT INTO cargo (id_cargo, nombre, descripcion) VALUES
    (1, 'Administrador', 'Acceso completo al sistema'),
    (2, 'Comprador', 'Gestion de catalogo y proveedores'),
    (3, 'Vendedor', 'Atencion al cliente y cotizaciones'),
    (4, 'Cajero', 'Punto de venta y facturacion'),
    (5, 'Bodeguero', 'Control de inventario fisico');

INSERT INTO metodo_pago (nombre) VALUES
    ('Efectivo'), ('Tarjeta Debito'), ('Tarjeta Credito'),
    ('Transferencia Bancaria'), ('Nequi / Daviplata');

INSERT INTO categoria (nombre, descripcion) VALUES
    ('Computadores', 'Laptops, desktops y workstations'),
    ('Celulares', 'Smartphones y tablets'),
    ('Accesorios', 'Perifericos, cables y accesorios varios'),
    ('Componentes', 'Hardware interno: RAM, discos, tarjetas'),
    ('Audio', 'Audifonos, parlantes y micros'),
    ('Redes', 'Routers, switches y cables de red');

-- Las contrasenas iniciales se conservan como hashes SHA-256 hexadecimales.
INSERT INTO persona (tipo, nombres, apellidos, documento, email, activo) VALUES
    ('EMPLEADO', 'Admin', 'TechZone', '10001', 'admin@techzone.co', TRUE),
    ('EMPLEADO', 'Oscar', 'Soto', '10002', 'osoto@techzone.co', TRUE),
    ('EMPLEADO', 'Leidy', 'Bustamante', '10003', 'lbustamante@techzone.co', TRUE),
    ('EMPLEADO', 'Carlos', 'Martinez', '10004', 'cmartinez@techzone.co', TRUE),
    ('EMPLEADO', 'Juan', 'Gaviria', '10005', 'jgaviria@techzone.co', TRUE),
    ('EMPLEADO', 'Alan', 'Caicedo', '10006', 'acaicedo@techzone.co', TRUE),
    ('CLIENTE', 'Laura', 'Gomez', '20001', 'laura@gmail.com', TRUE),
    ('CLIENTE', 'Pedro', 'Ramirez', '20002', 'pedro@gmail.com', TRUE);

INSERT INTO empleado (id_persona, id_cargo, contrasena_hash, salario)
SELECT id_persona, CASE documento
    WHEN '10001' THEN 1 WHEN '10002' THEN 2 WHEN '10003' THEN 3
    WHEN '10004' THEN 4 WHEN '10005' THEN 5 ELSE 3 END,
    encode(digest(CASE documento
        WHEN '10001' THEN 'admin123' WHEN '10002' THEN 'comprador123'
        WHEN '10003' THEN 'vendedor123' WHEN '10004' THEN 'techzone'
        WHEN '10005' THEN 'bodeguero123' ELSE 'alan123' END, 'sha256'), 'hex'),
    CASE documento WHEN '10001' THEN 5000000 ELSE 2000000 END
FROM persona WHERE tipo = 'EMPLEADO';

INSERT INTO cliente (id_persona, contrasena_hash)
SELECT id_persona, encode(digest(CASE documento
    WHEN '20001' THEN 'laura123' ELSE 'pedro123' END, 'sha256'), 'hex')
FROM persona WHERE tipo = 'CLIENTE';

INSERT INTO producto
    (id_categoria, nombre, descripcion, precio_compra, precio_venta, stock_actual, stock_minimo)
VALUES
    (1, 'Laptop ASUS VivoBook 15', 'Intel Core i5, 8GB RAM, 512GB SSD', 2200000, 2800000, 10, 3),
    (1, 'Laptop HP 15-dy', 'Intel Core i3, 8GB RAM, 256GB SSD', 1500000, 1900000, 8, 2),
    (2, 'Samsung Galaxy A55', 'Pantalla 6.6, 128GB, camara triple', 1100000, 1400000, 15, 5),
    (2, 'iPhone 15', 'Chip A16, 128GB', 4200000, 5100000, 6, 2),
    (3, 'Mouse Logitech MX Master 3', 'Inalambrico y ergonomico', 180000, 250000, 30, 8);


-- usuarios y contrasenas de prueba para la aplicacion Java, encriptadas con SHA-256:

-- Rol	        Correo	                Contraseña
--Administrador	admin@techzone.co	    admin123
--Comprador 	osoto@techzone.co	    comprador123
--Vendedor	    lbustamante@techzone.co	vendedor123
--Cajero	    cmartinez@techzone.co	techzone
--Bodeguero 	jgaviria@techzone.co	bodeguero123
--Vendedor 2	acaicedo@techzone.co	alan123